dist: trusty
sudo: false
group: beta
addons:
  apt:
    sources:
      - sourceline: 'ppa:milter-manager/ppa'
    packages:
      - rake
      - bison
      - git
      - gperf
      - automake
      - m4
      - autoreconf
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - libcunit1-dev
      - ragel
      - milter-manager

language: c
compiler:
  - gcc
  - clang
script:
  - make mruby
  - make 
  - make run &
  - make test
