dist: trusty
sudo: ture
group: beta
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
      - automake
      - m4
      - autoreconf
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - libcunit1-dev
      - ragel
      - milter-manager

language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:milter-manager/ppa
  - sudo apt-get update
  - sudo apt-get -V -y install milter-manager
script:
  - make mruby
  - make
  - make run &
  - make test
