dist: trusty
sudo: required
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:milter-manager/ppa
  - sudo apt-get update
  # for build
  - sudo apt-get -y install rake bison git gperf automake m4  autoconf libtool cmake pkg-config libcunit1-dev ragel
  # for test
  - sudo apt-get -y install ruby-milter-server ruby-milter-client
script:
  - make mruby
  - make
  - make run &
  # use system ruby gems
  - sudo make test
